### ISSUE TITLE
Updating docs

### ISSUE THREAD

**Issue by ixodie** [FRRouting/frr-www#23]
@jrrivers @mwinter-osr What is the proper method for updating these docs?  I need to replace a corporate logo.

I created a branch, replaced the logo, and tried to push the branch but it seems it is not allowed.

**Comment by jrrivers** [comment]
hmmmm... not sure why you can't push your branch... a couple of things a/
could try raising a PR and b/ LMK which logo to change and I'll do it for
you...

**Comment by ixodie** [comment]
It seems that the permissions do not allow me to upload a file, so my attempts to push my branch with the change are failing.

Either way, I only need to get the Netris icon changed to this.
![logo-300](https://user-images.githubusercontent.com/2715976/141979308-3a2f2fc7-d57f-4200-97cf-b2acddc0662e.png)

**Comment by qlyoung** [comment]
I updated it.
