### ISSUE TITLE
'Join with slack' link does not work, requires specific email domain to join

### ISSUE THREAD

**Issue by xrobau** [FRRouting/frr-www#44]
When clicking on it, it requires you to have an email address from a long (and somewhat random) list of domains.

**Comment by qlyoung** [comment]
Just to confirm, are you talking about [this](https://join.slack.com/t/frrouting/shared_invite/zt-1wjztl0jp-4hI5kBoSCtu8Eh_ILXdVlg) slack link found on [this page](https://frrouting.org/community/)?
![image](https://github.com/FRRouting/frr-www/assets/6827003/ccd15926-ce62-4f63-bd07-a6e1e9e84182)

**Comment by qlyoung** [comment]
No response

**Comment by kaffarell** [comment]
If you click on the link there is a list of allowed domains. Can we maybe add an email address of an administrator so that a new domain can be requested?
